config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  root 'pages#index'
  get 'pages/help'
  
  resources :users
  resources :museums
  resources :airplanes
  resources :posts
  resources :comments
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/museums/areas/:area', to: 'museums#areas'
  get '/museums/:id', to: 'museums#show'
  post '/post', to: 'post#create'
  get '/post/:id', to: 'post#index'
  
  post '/comments', to: 'comments#create'

  get '/mypage', to: 'users#mypage'
  get 'users/show', to: 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airplane.rb
class Airplane < ApplicationRecord
  has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/museum.rb
class Museum < ApplicationRecord
  has_many :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :description, presence: true
  validates :image, presence: true
  validates :museum_id, presence: true
  validates :airplane_id, presence: true
  
  belongs_to :user
  belongs_to :museum
  belongs_to :airplane
  has_many :comments, ->{ order( created_at: :DESC) }
  has_many :comment_users, through: :comments, source: 'user'

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 15 }
  validates :email, {presence: true, format: { with: VALID_EMAIL_REGEX }}
  validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX }
  
  has_secure_password
  
  has_many :posts
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  add_flash_types :success, :info, :warning, :danger
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end
  
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
   
    if @comment.save
      redirect_to posts_path, success: "コメントを投稿しました"
    else
      flash.now[:danger] = "コメントを投稿できませんでした"
      render :new
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit(:post_id, :content)
  end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  def index
  end
  
  def areas
    @area = params[:area]
    @museums = Museum.where(area: params[:area])
  end
  
  def show
    @posts = Post.where(museum_id: params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.new(post_params)
  
    if @post.save
      redirect_to posts_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:image, :description, :museum_id, :airplane_id, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: user_params[:email])
    if user && user.authenticate(user_params[:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash[:danger] = "ログインに失敗しました"
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end
  
  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def user_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  
  def show
  end
  
  def mypage
    redirect_to user_path(current_user)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
  
  def set_user
    @user = User.find(session[:user_id])

  end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
  
<div class="comment-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">コメント</h1>
        <%= form_for @comment do |f| %>
          <div class="form-group">
            <%= f.label :内容 %>
            <%= f.text_area :content, class: 'form-control' %>
          </div>
            <%= f.hidden_field :post_id, value: @post.id %>
          <% if logged_in? %>
            <%= f.submit 'コメントを投稿', class: 'btn btn-black btn-block' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/museums/areas.html.erb
<div class="museum-area-wrapper">
  <div class="container">
    <div class="row">
      <h2 class="museum-area">
        <%= @area %>
        <hr>
      </h2>
      <% @museums.each do |museum| %>
        <div class="museum-name">
          <a href="/museums/<%= museum.id %>"><%= museum.name %></a>
          <hr>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/museums/index.html.erb
<div class="museum-index-wrapper">
  <div class="container">
    <div class="row">
      <div class="form-group">
        <div class="museum-area"><a href="/museums/areas/東北">東北</a></div>
        <hr>
        <div class="museum-area"><a href="/museums/areas/関東">関東</a></div>
        <hr>
        <div class="museum-area"><a href="/museums/areas/中部">中部</a></div>
        <hr>
        <div class="museum-area"><a href="/museums/areas/近畿">近畿</a></div>
        <hr>
        <div class="museum-area"><a href="/museums/areas/四国">四国</a></div>
        <hr>
        <div class="museum-area"><a href="/museums/areas/九州">九州</a></div>
        <hr>
      </div>
    </div>
  </div>
</div>

app/views/museums/show.html.erb
<div class="post-index-wrapper">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="post-index-single">
            <h3 class="post-airplane">
              <%= post.airplane.name %>
            </h3>
            <a class="post-author"><%= post.user.name %></a>
            <p class="post-text"><%= post.description %></p>
            <%= image_tag post.image.url %>
            <%= link_to 'コメントする', new_comment_path(post_id: post.id), class: 'post-index' %>
            <h4 class="text-center">コメント</h4>
            <div class="post-index-comment">
              <% post.comments.each do |comment| %>
              <a class="comment-author"><%= comment.user.name %></a>
              <p class="comment-text"><%= comment.content %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="post-index-wrapper">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="post-index-single">
            <h3 class="post-airplane">
              <%= post.airplane.name %>
            </h3>
            <a href="/users/<%= post.user.id %>" class="post-author">
                <%= post.user.name %>
            </a>
            <p class="post-text">
              <%= post.description %>
            </p>
            <%= image_tag post.image.url %>
            <%= link_to 'コメントする', new_comment_path(post_id: post.id), class: 'post-index' %>
            <h4 class="text-center">コメント</h4>
            <div class="post-index-comment">
              <% post.comments.each do |comment| %>
              <a href="/users/<%= comment.user.id %>" class="comment-author"><%= comment.user.name %></a>
              <p class="comment-text"><%= comment.content %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="post-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">投稿</h1></h1>
        <%= form_for @post do |f| %>
          <div class="form-group">
            <%= f.label :画像 %>
            <%= f.file_field :image %>
          </div>
          <div class="form-group">
            <%= f.label :展示場 %>
            <%= f.collection_select :museum_id, Museum.all, :id, :name %>
          </div>
          <div class="form-group">
            <%= f.label :飛行機 %>
            <%= f.collection_select :airplane_id, Airplane.all, :id, :name %>
          </div>
          <div class="form-group">
            <%= f.label :概要 %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
        <% if logged_in? %>
          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center main-text">アカウント登録</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :アカウント名, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :メールアドレス, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :パスワード, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="users-show-wrapper">
  <div class="container">
    <div class="row">
       <div class="users-show-container">
          <h1 class="user-name">
            <%= @user.name %>
          </h1>
          <% if logged_in? && @user == current_user %>
            <h4 class="user-email">
              メールアドレス <%= @user.email %>
            </h4>
          <% end %>
       </div>
    </div>
  </div>
</div>