config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  root 'pages#index'
  get 'pages/help'
  
  resources :users
  resources :museums
  resources :airplanes
  resources :posts
  resources :comments
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/museums/areas/:area', to: 'museums#areas'
  get '/museums/:id', to: 'museums#show'
  post '/post', to: 'post#create'
  get '/post/:id', to: 'post#index'
  
  post '/comments', to: 'comments#create'

  get '/mypage', to: 'users#mypage'
  get 'users/show', to: 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airplane.rb
class Airplane < ApplicationRecord
  has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/museum.rb
class Museum < ApplicationRecord
  has_many :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :description, presence: true
  validates :image, presence: true
  validates :museum_id, presence: true
  validates :airplane_id, presence: true
  
  belongs_to :user
  belongs_to :museum
  belongs_to :airplane
  has_many :comments, ->{ order( created_at: :DESC) }
  has_many :comment_users, through: :comments, source: 'user'

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 15 }
  validates :email, {presence: true, format: { with: VALID_EMAIL_REGEX }}
  validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX }
  
  has_secure_password
  
  has_many :posts
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end
  
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
   
    if @comment.save
      redirect_to posts_path, success: "コメントを投稿しました"
    else
      flash.now[:danger] = "コメントを投稿できませんでした"
      render :new
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit(:post_id, :content)
  end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  def index
  end
  
  def areas
    @area = params[:area]
    @museums = Museum.where(area: params[:area])
  end
  
  def show
    @posts = Post.where(museum_id: params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.new(post_params)
  
    if @post.save
      redirect_to posts_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:image, :description, :museum_id, :airplane_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  
  def show
  end
  
  def mypage
    redirect_to user_path(current_user)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
  
  def set_user
    @user = User.find(session[:user_id])

  end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReconShots</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Recon Shots", root_path, class: 'navbar-title' %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to '投稿一覧', posts_path, class: 'navbar-btn' %>
            </li>
            <li>
              <%= link_to '展示場', museums_path, class: 'navbar-btn' %>
            </li>
          <% if logged_in? %>
            <li>
              <%= link_to '投稿',  new_post_path, class: 'navbar-btn' %>
            </li>
            <li>
              <%= link_to 'マイページ', mypage_path, class: 'navbar-btn' %>
            </li>
            <li>
              <%= link_to 'ログアウト', logout_path, method: :delete, class: 'navbar-btn' %>
            </li>
          <% else %>
            <li>
              <%= link_to '登録', new_user_path, class: 'navbar-btn' %>
            </li>
            <li>
              <%= link_to 'ログイン', login_path, class: 'navbar-btn' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <%= yield %>
    
    <script>
       $(function(){
          $(".alert").fadeOut(5000);
       });
    </script>
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページ</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container　top-hero-container">
    <% if logged_in? %>
      <div class="row">
        <h1 class="top-title">Recon Shots</h1>
        <%= link_to '軍用航空機の写真を共有しよう！', new_post_path, class: 'top-text'  %>
      </div>
    <% else %>
      <div class="row">
        <div class="col-md-offset-3 col-md-3">
          <%= link_to '登録', new_user_path, class: 'btn btn-block btn-white' %>
        </div>
        <div class="col-md-3">
          <%= link_to 'ログイン', login_path, class: 'btn btn-block btn-white' %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>